#!/usr/bin/env python
"""
Master geography for Maharashtra as MSRTC organises it.

  6 MSRTC regions -> 31 MSRTC divisions -> 36 revenue districts -> 358 talukas

Division list + region grouping: msrtc.maharashtra.gov.in/GeneralPages/Timetabel.aspx
(the official "ST Corporation Timetable" page, one PDF per division).
Districts / talukas: Government of Maharashtra district list, cross-checked
against en.wikipedia.org/wiki/List_of_talukas_of_Maharashtra.

Each taluka row: (English name, Marathi name, HQ town EN, HQ town MR)
HQ is omitted (None) when it equals the taluka name.

Writes data/msrtc/reference/geography.json. Run:  py scripts/geography/maharashtra_geography.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# (id, English, Marathi, Hindi, region, official timetable PDF file name)
DIVISIONS = [
    # Mumbai region
    ("mumbai", "Mumbai", "मुंबई", "मुंबई", "mumbai", "मुंबई_विभाग_वेळापत्रक.pdf"),
    ("thane", "Thane", "ठाणे", "ठाणे", "mumbai", "ठाणे_विभाग_वेळापत्रक.pdf"),
    ("palghar", "Palghar", "पालघर", "पालघर", "mumbai", "पालघर_विभाग_बसस्थानक_वेळापत्रक.pdf"),
    ("raigad", "Raigad", "रायगड", "रायगढ़", "mumbai", "रायगड_विभाग_वेळापत्रक.pdf"),
    ("ratnagiri", "Ratnagiri", "रत्नागिरी", "रत्नागिरी", "mumbai", "रत्नागिरी_विभाग_वेळापत्रक.pdf"),
    ("sindhudurg", "Sindhudurg", "सिंधुदुर्ग", "सिंधुदुर्ग", "mumbai", "सिंधुदुर्ग_विभाग_वेळापत्रक.pdf"),
    # Pune region
    ("pune", "Pune", "पुणे", "पुणे", "pune", "पुणे_विभाग_वेळापत्रक.pdf"),
    ("satara", "Satara", "सातारा", "सातारा", "pune", "सातारा_विभाग_वेळापत्रक.pdf"),
    ("sangli", "Sangli", "सांगली", "सांगली", "pune", "सांगली_विभाग_वेळापत्रक.pdf"),
    ("solapur", "Solapur", "सोलापूर", "सोलापुर", "pune", "सोलापूर_विभाग_बसस्थानक_वेळापत्रक.pdf"),
    ("kolhapur", "Kolhapur", "कोल्हापूर", "कोल्हापुर", "pune", "कोल्हापूर_विभाग_बसस्थानक_वेळापत्रक.pdf"),
    # Nashik region
    ("nashik", "Nashik", "नाशिक", "नासिक", "nashik", "नाशिक_विभाग_वेळापत्रक.pdf"),
    ("dhule", "Dhule", "धुळे", "धुले", "nashik", "धुळे_विभाग_वेळापत्रक.pdf"),
    ("jalgaon", "Jalgaon", "जळगाव", "जलगांव", "nashik", "जळगाव_विभाग_बस_स्थानक_वेळापत्रक.pdf"),
    ("ahilyanagar", "Ahilyanagar (Ahmednagar)", "अहिल्यानगर (अहमदनगर)", "अहिल्यानगर (अहमदनगर)", "nashik", "अहिल्यानगर_विभाग_वेळापत्रक.pdf"),
    # Chhatrapati Sambhajinagar region
    ("sambhajinagar", "Chhatrapati Sambhajinagar (Aurangabad)", "छत्रपती संभाजीनगर (औरंगाबाद)", "छत्रपति संभाजीनगर (औरंगाबाद)", "sambhajinagar", "छ_संभाजीनगर_विभाग_वेळापत्रक.pdf"),
    ("beed", "Beed", "बीड", "बीड", "sambhajinagar", "बीड_विभाग_वेळापत्रक.pdf"),
    ("jalna", "Jalna", "जालना", "जालना", "sambhajinagar", "जालना_विभाग_वेळापत्रक.pdf"),
    ("latur", "Latur", "लातूर", "लातूर", "sambhajinagar", "लातूर_विभाग_वेळापत्रक.pdf"),
    ("nanded", "Nanded", "नांदेड", "नांदेड़", "sambhajinagar", "नांदेड_विभाग_वेळापत्रक.pdf"),
    ("dharashiv", "Dharashiv (Osmanabad)", "धाराशिव (उस्मानाबाद)", "धाराशिव (उस्मानाबाद)", "sambhajinagar", "धाराशिव_विभाग_बसस्थानक_वेळापत्रक.pdf"),
    ("parbhani", "Parbhani", "परभणी", "परभणी", "sambhajinagar", "परभणी_विभाग_वेळापत्रक.pdf"),
    # Nagpur region
    ("nagpur", "Nagpur", "नागपूर", "नागपुर", "nagpur", "नागपूर_विभाग_बसस्थानक_वेळापत्रक.pdf"),
    ("bhandara", "Bhandara", "भंडारा", "भंडारा", "nagpur", "भंडारा_विभाग_वेळापत्रक.pdf"),
    ("wardha", "Wardha", "वर्धा", "वर्धा", "nagpur", "वर्धा_विभाग_वेळापत्रक.pdf"),
    ("chandrapur", "Chandrapur", "चंद्रपूर", "चंद्रपुर", "nagpur", "चंद्रपूर_बसस्थानक_वेळापत्रक.pdf"),
    ("gadchiroli", "Gadchiroli", "गडचिरोली", "गढ़चिरौली", "nagpur", "गडचिरोली_विभाग_वेळापत्रक.pdf"),
    # Amravati region
    ("amravati", "Amravati", "अमरावती", "अमरावती", "amravati", "अमरावती_विभाग_वेळापत्रक.pdf"),
    ("akola", "Akola", "अकोला", "अकोला", "amravati", "अकोला_विभाग_वेळापत्रक.pdf"),
    ("yavatmal", "Yavatmal", "यवतमाळ", "यवतमाल", "amravati", "यवतमाळ_विभाग_वेळापत्रक.pdf"),
    ("buldhana", "Buldhana", "बुलढाणा", "बुलढाणा", "amravati", "बुलढाणा_विभाग_वेळापत्रक.pdf"),
]

REGIONS = {
    "mumbai": ("Mumbai", "मुंबई"),
    "pune": ("Pune", "पुणे"),
    "nashik": ("Nashik", "नाशिक"),
    "sambhajinagar": ("Chhatrapati Sambhajinagar", "छत्रपती संभाजीनगर"),
    "nagpur": ("Nagpur", "नागपूर"),
    "amravati": ("Amravati", "अमरावती"),
}

# district id -> (English, Marathi, MSRTC division id, [talukas])
DISTRICTS = {
    "mumbai-city": ("Mumbai City", "मुंबई शहर", "mumbai", [
        ("Mumbai City", "मुंबई शहर", "Mumbai Central", "मुंबई सेंट्रल"),
    ]),
    "mumbai-suburban": ("Mumbai Suburban", "मुंबई उपनगर", "mumbai", [
        ("Kurla", "कुर्ला", None, None),
        ("Andheri", "अंधेरी", None, None),
        ("Borivali", "बोरिवली", None, None),
    ]),
    "thane": ("Thane", "ठाणे", "thane", [
        ("Thane", "ठाणे", None, None),
        ("Kalyan", "कल्याण", None, None),
        ("Murbad", "मुरबाड", None, None),
        ("Bhiwandi", "भिवंडी", None, None),
        ("Shahapur", "शहापूर", None, None),
        ("Ulhasnagar", "उल्हासनगर", None, None),
        ("Ambarnath", "अंबरनाथ", None, None),
    ]),
    "palghar": ("Palghar", "पालघर", "palghar", [
        ("Palghar", "पालघर", None, None),
        ("Vasai", "वसई", None, None),
        ("Dahanu", "डहाणू", None, None),
        ("Talasari", "तलासरी", None, None),
        ("Jawhar", "जव्हार", None, None),
        ("Mokhada", "मोखाडा", None, None),
        ("Vada", "वाडा", None, None),
        ("Vikramgad", "विक्रमगड", None, None),
    ]),
    "raigad": ("Raigad", "रायगड", "raigad", [
        ("Alibag", "अलिबाग", None, None),
        ("Pen", "पेण", None, None),
        ("Murud", "मुरुड", None, None),
        ("Panvel", "पनवेल", None, None),
        ("Uran", "उरण", None, None),
        ("Karjat", "कर्जत", None, None),
        ("Khalapur", "खालापूर", None, None),
        ("Mangaon", "माणगाव", None, None),
        ("Tala", "तळा", None, None),
        ("Roha", "रोहा", None, None),
        ("Sudhagad", "सुधागड", "Pali", "पाली"),
        ("Mahad", "महाड", None, None),
        ("Poladpur", "पोलादपूर", None, None),
        ("Shrivardhan", "श्रीवर्धन", None, None),
        ("Mhasala", "म्हसळा", None, None),
    ]),
    "ratnagiri": ("Ratnagiri", "रत्नागिरी", "ratnagiri", [
        ("Ratnagiri", "रत्नागिरी", None, None),
        ("Sangameshwar", "संगमेश्वर", "Devrukh", "देवरुख"),
        ("Lanja", "लांजा", None, None),
        ("Rajapur", "राजापूर", None, None),
        ("Chiplun", "चिपळूण", None, None),
        ("Guhagar", "गुहागर", None, None),
        ("Dapoli", "दापोली", None, None),
        ("Mandangad", "मंडणगड", None, None),
        ("Khed", "खेड", None, None),
    ]),
    "sindhudurg": ("Sindhudurg", "सिंधुदुर्ग", "sindhudurg", [
        ("Kankavli", "कणकवली", None, None),
        ("Vaibhavwadi", "वैभववाडी", None, None),
        ("Devgad", "देवगड", None, None),
        ("Malvan", "मालवण", None, None),
        ("Sawantwadi", "सावंतवाडी", None, None),
        ("Kudal", "कुडाळ", None, None),
        ("Vengurla", "वेंगुर्ला", None, None),
        ("Dodamarg", "दोडामार्ग", None, None),
    ]),
    "pune": ("Pune", "पुणे", "pune", [
        ("Pune City", "पुणे शहर", "Pune", "पुणे"),
        ("Haveli", "हवेली", "Pune", "पुणे"),
        ("Khed", "खेड", "Rajgurunagar", "राजगुरुनगर"),
        ("Junnar", "जुन्नर", None, None),
        ("Ambegaon", "आंबेगाव", "Ghodegaon", "घोडेगाव"),
        ("Maval", "मावळ", "Vadgaon Maval", "वडगाव मावळ"),
        ("Mulshi", "मुळशी", "Paud", "पौड"),
        ("Shirur", "शिरूर", None, None),
        ("Purandar", "पुरंदर", "Saswad", "सासवड"),
        ("Velhe (Rajgad)", "वेल्हे (राजगड)", "Velhe", "वेल्हे"),
        ("Bhor", "भोर", None, None),
        ("Baramati", "बारामती", None, None),
        ("Indapur", "इंदापूर", None, None),
        ("Daund", "दौंड", None, None),
    ]),
    "satara": ("Satara", "सातारा", "satara", [
        ("Satara", "सातारा", None, None),
        ("Jaoli", "जावळी", "Medha", "मेढा"),
        ("Koregaon", "कोरेगाव", None, None),
        ("Wai", "वाई", None, None),
        ("Mahabaleshwar", "महाबळेश्वर", None, None),
        ("Khandala", "खंडाळा", None, None),
        ("Phaltan", "फलटण", None, None),
        ("Man", "माण", "Dahiwadi", "दहिवडी"),
        ("Khatav", "खटाव", "Vaduj", "वडूज"),
        ("Patan", "पाटण", None, None),
        ("Karad", "कराड", None, None),
    ]),
    "sangli": ("Sangli", "सांगली", "sangli", [
        ("Miraj", "मिरज", None, None),
        ("Kavathe Mahankal", "कवठेमहांकाळ", None, None),
        ("Tasgaon", "तासगाव", None, None),
        ("Jat", "जत", None, None),
        ("Walwa", "वाळवा", "Islampur", "इस्लामपूर"),
        ("Shirala", "शिराळा", None, None),
        ("Khanapur", "खानापूर", "Vita", "विटा"),
        ("Atpadi", "आटपाडी", None, None),
        ("Palus", "पलूस", None, None),
        ("Kadegaon", "कडेगाव", None, None),
    ]),
    "solapur": ("Solapur", "सोलापूर", "solapur", [
        ("Solapur North", "उत्तर सोलापूर", "Solapur", "सोलापूर"),
        ("Solapur South", "दक्षिण सोलापूर", "Solapur", "सोलापूर"),
        ("Akkalkot", "अक्कलकोट", None, None),
        ("Barshi", "बार्शी", None, None),
        ("Mangalwedha", "मंगळवेढा", None, None),
        ("Pandharpur", "पंढरपूर", None, None),
        ("Sangola", "सांगोला", None, None),
        ("Malshiras", "माळशिरस", None, None),
        ("Mohol", "मोहोळ", None, None),
        ("Madha", "माढा", None, None),
        ("Karmala", "करमाळा", None, None),
    ]),
    "kolhapur": ("Kolhapur", "कोल्हापूर", "kolhapur", [
        ("Karvir", "करवीर", "Kolhapur", "कोल्हापूर"),
        ("Panhala", "पन्हाळा", None, None),
        ("Shahuwadi", "शाहूवाडी", "Malkapur", "मलकापूर"),
        ("Kagal", "कागल", None, None),
        ("Hatkanangle", "हातकणंगले", None, None),
        ("Shirol", "शिरोळ", None, None),
        ("Radhanagari", "राधानगरी", None, None),
        ("Gaganbawada", "गगनबावडा", None, None),
        ("Bhudargad", "भुदरगड", "Gargoti", "गारगोटी"),
        ("Gadhinglaj", "गडहिंग्लज", None, None),
        ("Chandgad", "चंदगड", None, None),
        ("Ajara", "आजरा", None, None),
    ]),
    "nashik": ("Nashik", "नाशिक", "nashik", [
        ("Nashik", "नाशिक", None, None),
        ("Igatpuri", "इगतपुरी", None, None),
        ("Dindori", "दिंडोरी", None, None),
        ("Peth", "पेठ", None, None),
        ("Trimbakeshwar", "त्र्यंबकेश्वर", None, None),
        ("Kalwan", "कळवण", None, None),
        ("Deola", "देवळा", None, None),
        ("Surgana", "सुरगाणा", None, None),
        ("Baglan", "बागलाण", "Satana", "सटाणा"),
        ("Malegaon", "मालेगाव", None, None),
        ("Nandgaon", "नांदगाव", None, None),
        ("Chandwad", "चांदवड", None, None),
        ("Niphad", "निफाड", None, None),
        ("Sinnar", "सिन्नर", None, None),
        ("Yeola", "येवला", None, None),
    ]),
    "dhule": ("Dhule", "धुळे", "dhule", [
        ("Dhule", "धुळे", None, None),
        ("Sakri", "साक्री", None, None),
        ("Shirpur", "शिरपूर", None, None),
        ("Shindkheda", "शिंदखेडा", None, None),
    ]),
    "nandurbar": ("Nandurbar", "नंदुरबार", "dhule", [
        ("Nandurbar", "नंदुरबार", None, None),
        ("Navapur", "नवापूर", None, None),
        ("Shahada", "शहादा", None, None),
        ("Taloda", "तळोदा", None, None),
        ("Akkalkuwa", "अक्कलकुवा", None, None),
        ("Akrani", "अक्राणी", "Dhadgaon", "धडगाव"),
    ]),
    "jalgaon": ("Jalgaon", "जळगाव", "jalgaon", [
        ("Jalgaon", "जळगाव", None, None),
        ("Jamner", "जामनेर", None, None),
        ("Erandol", "एरंडोल", None, None),
        ("Dharangaon", "धरणगाव", None, None),
        ("Bhusawal", "भुसावळ", None, None),
        ("Raver", "रावेर", None, None),
        ("Muktainagar", "मुक्ताईनगर", None, None),
        ("Bodwad", "बोदवड", None, None),
        ("Yawal", "यावल", None, None),
        ("Amalner", "अमळनेर", None, None),
        ("Parola", "पारोळा", None, None),
        ("Chopda", "चोपडा", None, None),
        ("Pachora", "पाचोरा", None, None),
        ("Bhadgaon", "भडगाव", None, None),
        ("Chalisgaon", "चाळीसगाव", None, None),
    ]),
    "ahilyanagar": ("Ahilyanagar", "अहिल्यानगर", "ahilyanagar", [
        ("Ahilyanagar", "अहिल्यानगर", None, None),
        ("Shevgaon", "शेवगाव", None, None),
        ("Pathardi", "पाथर्डी", None, None),
        ("Parner", "पारनेर", None, None),
        ("Sangamner", "संगमनेर", None, None),
        ("Kopargaon", "कोपरगाव", None, None),
        ("Akole", "अकोले", None, None),
        ("Shrirampur", "श्रीरामपूर", None, None),
        ("Nevasa", "नेवासा", None, None),
        ("Rahata", "राहाता", None, None),
        ("Rahuri", "राहुरी", None, None),
        ("Shrigonda", "श्रीगोंदा", None, None),
        ("Karjat", "कर्जत", None, None),
        ("Jamkhed", "जामखेड", None, None),
    ]),
    "sambhajinagar": ("Chhatrapati Sambhajinagar", "छत्रपती संभाजीनगर", "sambhajinagar", [
        ("Chhatrapati Sambhajinagar", "छत्रपती संभाजीनगर", None, None),
        ("Kannad", "कन्नड", None, None),
        ("Soegaon", "सोयगाव", None, None),
        ("Sillod", "सिल्लोड", None, None),
        ("Phulambri", "फुलंब्री", None, None),
        ("Khultabad", "खुलताबाद", None, None),
        ("Vaijapur", "वैजापूर", None, None),
        ("Gangapur", "गंगापूर", None, None),
        ("Paithan", "पैठण", None, None),
    ]),
    "jalna": ("Jalna", "जालना", "jalna", [
        ("Jalna", "जालना", None, None),
        ("Bhokardan", "भोकरदन", None, None),
        ("Jafrabad", "जाफराबाद", None, None),
        ("Badnapur", "बदनापूर", None, None),
        ("Ambad", "अंबड", None, None),
        ("Ghansawangi", "घनसावंगी", None, None),
        ("Partur", "परतूर", None, None),
        ("Mantha", "मंठा", None, None),
    ]),
    "beed": ("Beed", "बीड", "beed", [
        ("Beed", "बीड", None, None),
        ("Ashti", "आष्टी", None, None),
        ("Patoda", "पाटोदा", None, None),
        ("Shirur Kasar", "शिरूर कासार", None, None),
        ("Georai", "गेवराई", None, None),
        ("Majalgaon", "माजलगाव", None, None),
        ("Wadwani", "वडवणी", None, None),
        ("Kaij", "केज", None, None),
        ("Dharur", "धारूर", None, None),
        ("Parli", "परळी", "Parli Vaijnath", "परळी वैजनाथ"),
        ("Ambajogai", "अंबाजोगाई", None, None),
    ]),
    "latur": ("Latur", "लातूर", "latur", [
        ("Latur", "लातूर", None, None),
        ("Renapur", "रेणापूर", None, None),
        ("Ahmedpur", "अहमदपूर", None, None),
        ("Jalkot", "जळकोट", None, None),
        ("Chakur", "चाकूर", None, None),
        ("Shirur Anantpal", "शिरूर अनंतपाळ", None, None),
        ("Ausa", "औसा", None, None),
        ("Nilanga", "निलंगा", None, None),
        ("Deoni", "देवणी", None, None),
        ("Udgir", "उदगीर", None, None),
    ]),
    "dharashiv": ("Dharashiv", "धाराशिव", "dharashiv", [
        ("Dharashiv", "धाराशिव", None, None),
        ("Tuljapur", "तुळजापूर", None, None),
        ("Bhum", "भूम", None, None),
        ("Paranda", "परंडा", None, None),
        ("Washi", "वाशी", None, None),
        ("Kalamb", "कळंब", None, None),
        ("Lohara", "लोहारा", None, None),
        ("Umarga", "उमरगा", None, None),
    ]),
    "nanded": ("Nanded", "नांदेड", "nanded", [
        ("Nanded", "नांदेड", None, None),
        ("Ardhapur", "अर्धापूर", None, None),
        ("Bhokar", "भोकर", None, None),
        ("Biloli", "बिलोली", None, None),
        ("Deglur", "देगलूर", None, None),
        ("Dharmabad", "धर्माबाद", None, None),
        ("Hadgaon", "हदगाव", None, None),
        ("Himayatnagar", "हिमायतनगर", None, None),
        ("Kandhar", "कंधार", None, None),
        ("Kinwat", "किनवट", None, None),
        ("Loha", "लोहा", None, None),
        ("Mahur", "माहूर", None, None),
        ("Mudkhed", "मुदखेड", None, None),
        ("Mukhed", "मुखेड", None, None),
        ("Naigaon", "नायगाव", None, None),
        ("Umri", "उमरी", None, None),
    ]),
    "parbhani": ("Parbhani", "परभणी", "parbhani", [
        ("Parbhani", "परभणी", None, None),
        ("Gangakhed", "गंगाखेड", None, None),
        ("Sonpeth", "सोनपेठ", None, None),
        ("Pathri", "पाथरी", None, None),
        ("Manwat", "मानवत", None, None),
        ("Palam", "पालम", None, None),
        ("Selu", "सेलू", None, None),
        ("Jintur", "जिंतूर", None, None),
        ("Purna", "पूर्णा", None, None),
    ]),
    "hingoli": ("Hingoli", "हिंगोली", "parbhani", [
        ("Hingoli", "हिंगोली", None, None),
        ("Sengaon", "सेनगाव", None, None),
        ("Kalamnuri", "कळमनुरी", None, None),
        ("Basmat", "वसमत", None, None),
        ("Aundha Nagnath", "औंढा नागनाथ", None, None),
    ]),
    "nagpur": ("Nagpur", "नागपूर", "nagpur", [
        ("Nagpur Urban", "नागपूर शहर", "Nagpur", "नागपूर"),
        ("Nagpur Rural", "नागपूर ग्रामीण", "Nagpur", "नागपूर"),
        ("Kamptee", "कामठी", None, None),
        ("Hingna", "हिंगणा", None, None),
        ("Katol", "काटोल", None, None),
        ("Narkhed", "नरखेड", None, None),
        ("Savner", "सावनेर", None, None),
        ("Kalmeshwar", "कळमेश्वर", None, None),
        ("Ramtek", "रामटेक", None, None),
        ("Mouda", "मौदा", None, None),
        ("Parseoni", "पारशिवनी", None, None),
        ("Umred", "उमरेड", None, None),
        ("Kuhi", "कुही", None, None),
        ("Bhiwapur", "भिवापूर", None, None),
    ]),
    "wardha": ("Wardha", "वर्धा", "wardha", [
        ("Wardha", "वर्धा", None, None),
        ("Deoli", "देवळी", None, None),
        ("Seloo", "सेलू", None, None),
        ("Arvi", "आर्वी", None, None),
        ("Ashti", "आष्टी", None, None),
        ("Karanja", "कारंजा (घाडगे)", "Karanja Ghadge", "कारंजा घाडगे"),
        ("Hinganghat", "हिंगणघाट", None, None),
        ("Samudrapur", "समुद्रपूर", None, None),
    ]),
    "bhandara": ("Bhandara", "भंडारा", "bhandara", [
        ("Bhandara", "भंडारा", None, None),
        ("Tumsar", "तुमसर", None, None),
        ("Pauni", "पवनी", None, None),
        ("Mohadi", "मोहाडी", None, None),
        ("Sakoli", "साकोली", None, None),
        ("Lakhani", "लाखनी", None, None),
        ("Lakhandur", "लाखांदूर", None, None),
    ]),
    "gondia": ("Gondia", "गोंदिया", "bhandara", [
        ("Gondia", "गोंदिया", None, None),
        ("Goregaon", "गोरेगाव", None, None),
        ("Salekasa", "सालेकसा", None, None),
        ("Tirora", "तिरोडा", None, None),
        ("Amgaon", "आमगाव", None, None),
        ("Deori", "देवरी", None, None),
        ("Arjuni Morgaon", "अर्जुनी मोरगाव", None, None),
        ("Sadak Arjuni", "सडक अर्जुनी", None, None),
    ]),
    "chandrapur": ("Chandrapur", "चंद्रपूर", "chandrapur", [
        ("Chandrapur", "चंद्रपूर", None, None),
        ("Saoli", "सावली", None, None),
        ("Mul", "मूल", None, None),
        ("Ballarpur", "बल्लारपूर", None, None),
        ("Pombhurna", "पोंभुर्णा", None, None),
        ("Gondpipri", "गोंडपिपरी", None, None),
        ("Warora", "वरोरा", None, None),
        ("Chimur", "चिमूर", None, None),
        ("Bhadravati", "भद्रावती", None, None),
        ("Brahmapuri", "ब्रह्मपुरी", None, None),
        ("Nagbhid", "नागभीड", None, None),
        ("Sindewahi", "सिंदेवाही", None, None),
        ("Rajura", "राजुरा", None, None),
        ("Korpana", "कोरपना", None, None),
        ("Jiwati", "जिवती", None, None),
    ]),
    "gadchiroli": ("Gadchiroli", "गडचिरोली", "gadchiroli", [
        ("Gadchiroli", "गडचिरोली", None, None),
        ("Dhanora", "धानोरा", None, None),
        ("Chamorshi", "चामोर्शी", None, None),
        ("Mulchera", "मुलचेरा", None, None),
        ("Desaiganj", "देसाईगंज", "Wadsa", "वडसा"),
        ("Armori", "आरमोरी", None, None),
        ("Kurkheda", "कुरखेडा", None, None),
        ("Korchi", "कोरची", None, None),
        ("Aheri", "अहेरी", None, None),
        ("Etapalli", "एटापल्ली", None, None),
        ("Bhamragad", "भामरागड", None, None),
        ("Sironcha", "सिरोंचा", None, None),
    ]),
    "amravati": ("Amravati", "अमरावती", "amravati", [
        ("Amravati", "अमरावती", None, None),
        ("Bhatkuli", "भातकुली", None, None),
        ("Nandgaon Khandeshwar", "नांदगाव खंडेश्वर", None, None),
        ("Dharni", "धारणी", None, None),
        ("Chikhaldara", "चिखलदरा", None, None),
        ("Achalpur", "अचलपूर", "Paratwada", "परतवाडा"),
        ("Chandur Bazar", "चांदूर बाजार", None, None),
        ("Morshi", "मोर्शी", None, None),
        ("Warud", "वरूड", None, None),
        ("Daryapur", "दर्यापूर", None, None),
        ("Anjangaon Surji", "अंजनगाव सुर्जी", None, None),
        ("Chandur Railway", "चांदूर रेल्वे", None, None),
        ("Dhamangaon Railway", "धामणगाव रेल्वे", None, None),
        ("Teosa", "तिवसा", None, None),
    ]),
    "akola": ("Akola", "अकोला", "akola", [
        ("Akola", "अकोला", None, None),
        ("Akot", "अकोट", None, None),
        ("Telhara", "तेल्हारा", None, None),
        ("Balapur", "बाळापूर", None, None),
        ("Patur", "पातूर", None, None),
        ("Murtijapur", "मूर्तिजापूर", None, None),
        ("Barshitakli", "बार्शीटाकळी", None, None),
    ]),
    "washim": ("Washim", "वाशिम", "akola", [
        ("Washim", "वाशिम", None, None),
        ("Malegaon", "मालेगाव", None, None),
        ("Risod", "रिसोड", None, None),
        ("Mangrulpir", "मंगरूळपीर", None, None),
        ("Karanja", "कारंजा", "Karanja Lad", "कारंजा लाड"),
        ("Manora", "मानोरा", None, None),
    ]),
    "buldhana": ("Buldhana", "बुलढाणा", "buldhana", [
        ("Buldhana", "बुलढाणा", None, None),
        ("Chikhli", "चिखली", None, None),
        ("Deulgaon Raja", "देऊळगाव राजा", None, None),
        ("Jalgaon Jamod", "जळगाव जामोद", None, None),
        ("Sangrampur", "संग्रामपूर", None, None),
        ("Malkapur", "मलकापूर", None, None),
        ("Motala", "मोताळा", None, None),
        ("Nandura", "नांदुरा", None, None),
        ("Khamgaon", "खामगाव", None, None),
        ("Shegaon", "शेगाव", None, None),
        ("Mehkar", "मेहकर", None, None),
        ("Sindkhed Raja", "सिंदखेड राजा", None, None),
        ("Lonar", "लोणार", None, None),
    ]),
    "yavatmal": ("Yavatmal", "यवतमाळ", "yavatmal", [
        ("Yavatmal", "यवतमाळ", None, None),
        ("Arni", "आर्णी", None, None),
        ("Babhulgaon", "बाभूळगाव", None, None),
        ("Kalamb", "कळंब", None, None),
        ("Darwha", "दारव्हा", None, None),
        ("Digras", "दिग्रस", None, None),
        ("Ner", "नेर", None, None),
        ("Pusad", "पुसद", None, None),
        ("Umarkhed", "उमरखेड", None, None),
        ("Mahagaon", "महागाव", None, None),
        ("Kelapur", "केळापूर", "Pandharkawada", "पांढरकवडा"),
        ("Ralegaon", "राळेगाव", None, None),
        ("Ghatanji", "घाटंजी", None, None),
        ("Wani", "वणी", None, None),
        ("Maregaon", "मारेगाव", None, None),
        ("Zari Jamani", "झरी जामणी", None, None),
    ]),
}


def slug(s: str) -> str:
    import re
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def build() -> dict:
    div_ids = {d[0] for d in DIVISIONS}
    districts, talukas = [], []
    for did, (en, mr, div, tl) in DISTRICTS.items():
        assert div in div_ids, div
        districts.append({"id": did, "name": en, "nameMr": mr, "division": div, "talukas": len(tl)})
        for (ten, tmr, hq, hqmr) in tl:
            talukas.append({
                "id": f"{did}--{slug(ten)}",
                "name": ten, "nameMr": tmr,
                "district": did, "districtName": en, "division": div,
                "hq": hq or ten, "hqMr": hqmr or tmr,
            })
    divisions = [
        {"id": i, "name": en, "nameMr": mr, "nameHi": hi, "slug": i, "region": rg,
         "regionName": REGIONS[rg][0], "regionNameMr": REGIONS[rg][1],
         "timetablePdf": f"https://msrtc.maharashtra.gov.in/pdf/MSRTC-Timetabel/{pdf}",
         "districts": [d["id"] for d in districts if d["division"] == i]}
        for (i, en, mr, hi, rg, pdf) in DIVISIONS
    ]
    # The PDF URLs sit in a region folder; fix them up from the known layout.
    folder = {"mumbai": "मुंबई_विभाग", "pune": "पुणे_विभाग", "nashik": "नाशिक_विभाग",
              "sambhajinagar": "छ_संभाजीनगर_विभाग", "nagpur": "नागपूर_विभाग", "amravati": "अमरावती_विभाग"}
    for d, row in zip(divisions, DIVISIONS):
        d["timetablePdf"] = f"https://msrtc.maharashtra.gov.in/pdf/MSRTC-Timetabel/{folder[row[4]]}/{row[5]}"
    return {"divisions": divisions, "districts": districts, "talukas": talukas}


if __name__ == "__main__":
    g = build()
    out = ROOT / "data" / "msrtc" / "reference" / "geography.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(g, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"divisions={len(g['divisions'])} districts={len(g['districts'])} talukas={len(g['talukas'])} -> {out}")
